### ISSUE TITLE
i am getting error regarding ur bot

### ISSUE THREAD

**Issue by ShrimantaGarain** [impshum/reddit-daily-image#1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\shrim\Downloads\Compressed\reddit-daily-image-master\reddit-daily-image-master\run.py", line 61, in runner
    job_func()
  File "c:\Users\shrim\Downloads\Compressed\reddit-daily-image-master\reddit-daily-image-master\run.py", line 72, in main
    reddit.subreddit(reddit_target_subreddit).submit_image(title, image)
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\praw\models\reddit\subreddit.py", line 1188, in submit_image
    image_url, websocket_url = self._upload_media(
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\praw\models\reddit\subreddit.py", line 690, in _upload_media
    upload_response = self._reddit.post(url, data=img_data)
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\praw\reddit.py", line 760, in post
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\prawcore\rate_limit.py", line 33, in call    kwargs["headers"] = set_header_callback()
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\prawcore\sessions.py", line 283, in _set_header_callback    self._authorizer.refresh()
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\prawcore\auth.py", line 425, in refresh    self._request_token(
  File "C:\Users\shrim\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\prawcore\auth.py", line 158, in _request_token    raise OAuthException(prawcore.exceptions.OAuthException: invalid_grant error processing request

**Comment by impshum** [comment]
I just tested the script and it's working fine. The problem is with your keys.

**Comment by ShrimantaGarain** [comment]
yaa bro mybad!  .........is there any way to post multiple images at once? will we very thankfull if u help
